### ISSUE TITLE
A simple way to download the dataset

### ISSUE THREAD

**Issue by geoexploring** [calebrob6/dfc2021-msd-baseline#2]
Thanks for sharing !
Could you please provide a simple  way to download the dataset (Not Microsoft Azure) ?
thanks

**Comment by calebrob6** [comment]
Hi @geoexploring,

We list several ways to download the dataset [on the competition page](http://www.grss-ieee.org/community/technical-committees/data-fusion/2021-ieee-grss-data-fusion-contest-track-msd/).

IMO, the most simple way would be to download the [index file](https://dfc2021.blob.core.windows.net/competition-data/dfc2021_index.txt) and run something like `wget -i dfc2021_index.txt`.

The method using [azcopy](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10) is also very easy (you simply need to download the azcopy tool and run the command specified on the competition page).

Best,
Caleb

**Comment by geoexploring** [comment]
Thank you for the details, @calebrob6 ，

Since I don't have the habit of using credit cards, I find it troublesome to download using Azure (Azcopy download requires Azure registration, and Azure registration requires credit card).

I will try `wget`, thanks.

**Comment by calebrob6** [comment]
No it doesn't, you can simply download `azcopy` as a zip file from this page -- https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10 -- see:

![image](https://user-images.githubusercontent.com/1088078/103854724-0672b880-5066-11eb-88e0-e987117c1ebe.png)

**Comment by geoexploring** [comment]
Sorry for my late reply.

I understand what you mean, I have downloaded the Azcopy yesterday.

I'm new to Azcopy, so I referred to [this article](https://adamtheautomator.com/azcopy-setup/) to learn how to use Azcopy. As the article stated, using Azcopy requires registration for Azure, but I found out during the registration process that needs a credit card.

I've downloaded the dataset using `wget-i dfc2021_index.txt`, which is easy.

Thank you for your prompt reply. Please correct me if I make any mistakes.

**Comment by calebrob6** [comment]
It is true that you need to authenticate azcopy to use some of the functionality (and therefore need an Azure account) as azcopy is made for managing resources on Azure. However, it is not true in this case (I've included a read only SAS key in the copy command).

If you simply run the command that we included in the download instructions you'll find it works without needing an Azure account (by design).

**Comment by geoexploring** [comment]
Thank you for your reply. 

I have downloaded and installed azcopy, but when I run the provided command：
`azcopy copy –recursive “https://dfc2021.blob.core.windows.net/competition-data/?sv=2019-12-12&ss=b&srt=co&sp=rlx&se=2021-11-30T07:59:10Z&st=2020-11-29T23:59:10Z&spr=https&sig=7gHwFEikxkt4uYU1Rdr9ngEUPqJmSQTxab6x6aKfEzs%3D” "Mypath/dataset/"`
 I get an error: `Unknown Shorthand Flag:' R 'in -Recursive`.

Did I misunderstand something?  thanks

**Comment by geoexploring** [comment]
I got it！

It is a string problem, the correct command is: `azcopy copy --recursive "https://dfc2021.blob.core.windows.net/competition-data/?sv=2019-12-12&ss=b&srt=co&sp=rlx&se=2021-11-30T07:59:10Z&st=2020-11-29T23:59:10Z&spr=https&sig=7gHwFEikxkt4uYU1Rdr9ngEUPqJmSQTxab6x6aKfEzs%3D" "H:\MSCD_dataset"`

Thank you very much, azcopy is the easiest way.

**Comment by calebrob6** [comment]
Oh good catch! Thank you for pointing this typo out.
